import Head from 'next/head'
import Advantages from '@/components/advantages/Advantages'
import advantagesStyles from '../components/advantages/Advantages.module.css'
import Hero from '@/components/hero/Hero'
import Culture from '@/components/about/Culture'
import Products from '@/components/products/Products'
import productsStyles from '../components/products/Products.module.css'
import Comparation from '@/components/comparation/Comparation'
import Picture from '@/components/Picture'
import OurPartners from '@/components/brands/OurPartners'
import OurStore from '@/components/store/OurStore'
import Footer from '@/components/footer/Footer'
import PhotosStore from '@/components/photos_store/PhotosStore'
import Whatsapp from '@/components/whatsapp_section/Whatsapp'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </Head>
      <main>
        {/* <Hero /> */}
        <Hero />

        {/* Cards  */}
        <section className={advantagesStyles.advantages}>
          <Advantages
            icon="bx bxs-check-circle"
            title="FÁCIL RETORNO"
            text="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo maiores laudantium asperiores blanditiis fugiat reiciendis, commodi ut nisi unde quis."
            cardStyle={advantagesStyles.card}
            iconStyle={advantagesStyles.icon}
          />
          <Advantages
            title="BUENOS PRECIOS"
            text="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo maiores laudantium asperiores blanditiis fugiat reiciendis, commodi ut nisi unde quis."
            icon="bx bxs-wallet"
            cardStyle={advantagesStyles.card}
            iconStyle={advantagesStyles.icon}
          />
          <Advantages
            title="PRODUCTOS GARANTIZADOS"
            text="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nemo maiores laudantium asperiores blanditiis fugiat reiciendis, commodi ut nisi unde quis."
            icon="bx bxs-certification"
            cardStyle={advantagesStyles.alternativeCard}
            iconStyle={advantagesStyles.alternativeIcon}
          />
        </section>

        {/* Culture  */}
        <Culture />

        {/* Products  */}
        <section>
          <div className={productsStyles.titleProducts}>
            <h3>Categorías</h3>
            <h2>SELECCIÓN DE PRODUCTOS</h2>
          </div>

          <section className={productsStyles.sectionContainer}>
            <Products
              className={productsStyles.sectionContainer}
              title="Esencias"
              text="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos cumque
              laborum ipsam"
              img="https://templatekit.jegtheme.com/jevape/wp-content/uploads/sites/126/2021/07/electronic-cigarette-and-liquid-with-clouds-of-smoke-on-dark-background-e1626674164870-614x1024.jpg"
              alt="esencias de vaporizador"
            />
            <Products
              className={productsStyles.sectionContainer}
              title="Desechables"
              text="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos cumque
              laborum ipsam"
              img="https://templatekit.jegtheme.com/jevape/wp-content/uploads/sites/126/2021/07/vaping-device-2-614x1024.jpg"
              alt="vaporizadores desechables"
            />
            <Products
              className={productsStyles.sectionContainer}
              title="Accesorios"
              text="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos cumque
              laborum ipsam"
              img="https://templatekit.jegtheme.com/jevape/wp-content/uploads/sites/126/2021/07/vape-accesories-614x1024.jpg"
              alt="accesorios de vaporizadores"
            />
            <Products
              className={productsStyles.sectionContainer}
              title="Kit de inicio"
              text="Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos cumque
              laborum ipsam"
              img="https://templatekit.jegtheme.com/jevape/wp-content/uploads/sites/126/2021/07/vape-starter-kit-614x1024.jpg"
              alt="kits de vaporizadores"
            />
          </section>
        </section>

        {/* Smoke vs Vaping  */}
        <Comparation />

        {/* Picture  */}
        <Picture />

        {/* Brands  */}
        <OurPartners />

        {/*  Our Store */}
        <OurStore />

        <PhotosStore />

        {/* Contact  */}
        <Whatsapp />

        {/* Footer  */}
        <Footer />
      </main>
    </>
  )
}
